project:
  type: website
  output-dir: docs
website:
  title: "ML"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    tools:
      - icon: twitter
        href: https://twitter.com/seyidasho/
      - icon: linkedin
        href: www.linkedin.com/in/seyidasho/
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/seyidasho/ML_Basics
  sidebar:
    style: docked
    contents:
      - section: "Fundamentals"
        contents:
          - href: intro.qmd
      - section: "Topics"
        contents:
          - href: Prob_Theory_Rnd.qmd
          - href: clustering.qmd
          - href: L_NL_Regression.qmd
          - href: Classification.qmd
          - href: Anomaly_Detection.qmd
  back-to-top-navigation: true    
  page-footer: "Copyright 2023, Oluwaseyi Dasho"


